apiVersion: v1
kind: Pod
metadata:
  name: flipkartvolume
spec:
  containers:
    - name: c00
      image: centos
      command: ["/bin/bash", "-c", "sleep 15000"]
      volumeMounts:
        - name: kp
          mountPath: "/tmp/signup"

    - name: c01
      image: centos
      command: ["/bin/bash", "-c", "sleep 10000"]
      volumeMounts:
        - name: kp
          mountPath: "/tmp/login"

  volumes:
    - name: kp
      emptyDir: {}
