apiVersion: v1
kind: Pod
metadata:
  name: flipkart
spec:
  containers:
    - name: signup
      image: centos
      command: ["/bin/bash", "-c", "sleep 15000"]
      volumeMounts:
        - name: kp
          mountPath: /tmp/hostpath

  volumes:
    - name: kp
      hostPath:
        path: /tmp/data
